site_name: My Docs
theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    # - navigation.expand
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Perguntas frequentes:
    - index.md
    - Qual linguagem começar?:
      - index.md
    - Python/Java/PHP/Javascript são boas? Qual a melhor?:
      - index.md
    - Qual linguagem começar?:
      - index.md
    - Que projeto eu desenvolvo para o meu portfólio?:
      - index.md
    - Quanto tempo leva para conseguir um estágio/emprego?:
      - index.md
    - Preciso de faculdade para ser programador?:
      - index.md
    - Qual a diferença entre os cursos de Engenharia de Software e da Computação, CC, SI e ADS?:
      - index.md
    - Front-end ou back-end?:
      - index.md
    - Posso usar o ChatGPT para codar?:
      - index.md
    - As inteligências artificiais vão tirar o emprego do programador?:
      - index.md
    - Onde procurar emprego?:
      - index.md
    - Como fazer uma entrevista de emprego?:
      - index.md
    - Meu portfólio/currículo/linkedin tá bom?:
      - index.md
    - Qual o melhor curso?:
      - index.md
    - Preciso saber inglês para programar?:
      - index.md
    - Preciso saber matemática para programar?:
      - index.md
  - Primeiros Passos:
    - index.md 
    - Não sei nem mexer em computador ainda:
      - index.md
    - Tópicos básicos de computação:
      - index.md
    - Projetos básicos:
      - index.md
    - Tópicos avançados de computação:
      - inicio/teoria/index.md
    - Projetos avançados:
      - index.md

  - HTML e CSS:
    - index.md 
    # - Tópicos básicos:
    #   - index.md
    #   - HTML e CSS:
    #     - index.md
    # - Tópicos intermediários:
    #   - index.md
    #   - Bootstrap:
    #     - index.md
    - Página de Preços: html/precos.md
  - Javascript:
    - index.md 
    # - Material de apoio:
    #   - index.md
    #   - Cursos e apostilas:
    #     - index.md
    #   - Códigos para leitura:
    #     - index.md
    # - Projetos:
    #   - index.md
    - Leitura de códigos: javascript/leitura.md
    - Testes automatizados: javascript/testes.md
    - Resolução de problemas: javascript/problemas.md
    - Manipulador de arquivos: javascript/manipulador_arquivos.md
  - Front-end:
    - index.md 
    # - Material de apoio:
    #   - index.md
    #   - Manipulação do DOM:
    #     - index.md
    #   - DevTools:
    #     - index.md
    #   - HTTP e API clients:
    #     - index.md
    #   - Playwright:
    #     - index.md
    # - Projetos:
    #   - index.md
    - Manipulação do DOM: front/dom.md # - Exercícios, Leitura e modificar códigos que manipulam o DOM
    - Leitura e modificação de códigos: front/leitura.md # - Exercícios, Leitura e modificar códigos que manipulam o DOM
    - Interação com uma API fake:
      - index.md
      - Usando uma API client: front/api/client.md
      - Usando Javascript: front/api/javascript.md
      - HTML / CSS / JS: front/api/projeto.md
      - Teste E2E com Playwright: front/api/test.md
  - Back-end:
    - index.md 
    # - Material de apoio:
    #   - index.md
    #   - Node.js:
    #     - index.md
    #   - REST APIs:
    #     - index.md
    #   - Express.js:
    #     - index.md
    #   - Banco de dados:
    #     - index.md
    #   - Supertest:
    #     - index.md
    # - Projetos:
    #   - index.md
    - Leitura de códigos: back/leitura.md
    - Servidor API fake: back/api.md
    - Banco de dados: back/database.md
    - Adicionar nova funcionalidade: back/novas_funcionalidades.md
  - Front-end com framework:
    - index.md 
    # - Material de apoio:
    #   - index.md
    #   - React.JS:
    #     - index.md
    #   - Técnicas:
    #     - index.md
    #     - Testes automatizados:
    #       - index.md
    #     - Roteamento:
    #       - index.md
    #     - Comunicação com APIs: // default, isError, error, isLoading, isSuccess, data
    #       - index.md
    #     - Gerenciamento de Estados:
    #       - index.md
    #     - Estilização dinâmica:
    #       - index.md
    #     - Formulários:
    #       - index.md
    #     - Suspense:
    #       - index.md
    #   - Bibliotecas:
    #     - index.md
    #     - React Router:
    #       - index.md
    #     - Tanstack Query:
    #       - index.md
    #     - Zustand:
    #       - index.md
    #   - Testes automatizados:
    #     - index.md
    # - Projetos:
    #   - index.md
    - Técnicas e biblioteca: # leitura e exercícios p implementar as técnicas do 0 e usando bibliotecas
      - index.md
      # - Dicionário:
      #   - index.md
      - Técnicas: index.md # leitura, exercícios e modificar
      - Bibliotecas: index.md # leitura, exercícios e modificar
    - Desafios de contratação de empresas:
      - index.md
  - Back-end com framework:
    - index.md 
    # - Material de apoio:
    #   - index.md

    #   - Linguagem de programação:
    #     - index.md
    #     - PHP / Java / C# / Python:
    #       - index.md
    #     - Orientação a Objetos:
    #       - index.md


    #   - Banco de Dados:
    #     - index.md
    #     - Relacionamentos:
    #       - index.md
    #     - Modelagem:
    #       - index.md
    #     - ORMs:
    #       - index.md
    #     - Migrations:
    #       - index.md
    #     - Seeds, Factories:
    #       - index.md

    #   - Aplicação:
    #     - index.md
    #     - Testing:
    #       - index.md
    #     - Roteamento:
    #       - index.md
    #     - Middlewares:
    #       - index.md
    #     - Autenticação:
    #       - index.md
    #     - Validação:
    #       - index.md
    #     - Templates:
    #       - index.md
    #     - Paginação:
    #       - index.md
    #     - Debugging:
    #       - index.md
    #     - Logging:
    #       - index.md

    #   - Outros:
    #     - index.md
    #     - Documentação da API:
    #       - index.md
    #     - Login com Google:
    #       - index.md
    #     - Websockets:
    #       - index.md
    #     - Envio de E-mail:
    #       - index.md
    #     - Integração com Meios de Pagamento:
    #       - index.md
    #     - Web Scrapping:
    #       - index.md
    #     - OAuth2.0:
    #       - index.md

    #   - Infraestrutura:
    #     - index.md
    #     - Docker:
    #       - index.md
    #     - GitHub Actions:
    #       - index.md
    #     - AWS:
    #       - index.md
    #     - Monitoramento:
    #       - index.md

        
    # - Projetos:
    #   - index.md
    - Leitura e exercícios de frameworks minimalistas:
      - index.md
    - Leitura e exercícios de Spring / .NET / NestJS / Laravel / Django:
      - index.md
    # - Dicionário:
    #   - index.md
    - Modificar códigos:
      - index.md
    - Desafios de contratação de empresas:
      - index.md
    - OAuth2.0 server: # servidor de emissão + servidor de recursos + client
      - index.md
    - Web Scrapper:
      - index.md
  - Portfólio:
    - index.md 
    - Projetos: 
      - index.md
  # - Tópicos avançados:
  #   - index.md
  #   - HTML e CSS:
  #     - Boas práticas:
  #       - index.md
  #     - Reutilização de componentes:
  #       - index.md
  #     - Arquiteturas e ferramentas:
  #       - index.md
  #     - Tailwind:
  #       - index.md
  #     - Outros frameworks:
  #       - index.md
  #     - Projetos de aprofundamento:
  #       - index.md
  #       - Prática com arquiteturas e frameworks:
  #         - index.md
  #       - Réplicas de websites:
  #         - index.md
  #   - Linguagens de programação:
  #       - index.md
  #       - Tópicos:
  #         - index.md
  #         - Organização e arquitetura de computadores:
  #           - index.md
  #         - Sistemas operacionais:
  #           - index.md
  #         - Linguagem C:
  #           - index.md
  #         - Algoritmos e estrutura de dados:
  #           - index.md
  #         - Linguagens e Compiladores:
  #           - index.md
  #         - Matemática para computação:
  #           - index.md
  #       - Projetos:
  #         - index.md
  #         - Resolução de problemas de nível médio/avançado no LeetCode:
  #           - index.md
  #         - Visualizador de algoritmos:
  #           - index.md
  #         - Escrever código em Assembly:
  #           - index.md
  #         - Construir um software complexo:
  #           - index.md
  #           - Linguagem de programação:
  #             - index.md
  #           - TCP server/client:
  #             - index.md
  #           - Sistema de controle de versões:
  #             - index.md